export const FETCH_DASHBOARDS_REQUEST = "FETCH_DASHBOARDS_REQUEST";
export const FETCH_DASHBOARDS_SUCCESS = "FETCH_DASHBOARDS_SUCCESS";
export const FETCH_DASHBOARDS_FAILURE = "FETCH_DASHBOARDS_FAILURE";

export const FETCH_DASHBOARD_REQUEST = "FETCH_DASHBOARD_REQUEST";
export const FETCH_DASHBOARD_SUCCESS = "FETCH_DASHBOARD_SUCCESS";
export const FETCH_DASHBOARD_FAILURE = "FETCH_DASHBOARD_FAILURE";