export const FETCH_DEPOSITS_REQUEST = "FETCH_DEPOSITS_REQUEST";
export const FETCH_DEPOSITS_SUCCESS = "FETCH_DEPOSITS_SUCCESS";
export const FETCH_DEPOSITS_FAILURE = "FETCH_DEPOSITS_FAILURE";

export const FETCH_DEPOSIT_REQUEST = "FETCH_DEPOSIT_REQUEST";
export const FETCH_DEPOSIT_SUCCESS = "FETCH_DEPOSIT_SUCCESS";
export const FETCH_DEPOSIT_FAILURE = "FETCH_DEPOSIT_FAILURE";