export const FETCH_FINDS_REQUEST = "FETCH_FINDS_REQUEST";
export const FETCH_FINDS_SUCCESS = "FETCH_FINDS_SUCCESS";
export const FETCH_FINDS_FAILURE = "FETCH_FINDS_FAILURE";

export const FETCH_FIND_REQUEST = "FETCH_FIND_REQUEST";
export const FETCH_FIND_SUCCESS = "FETCH_FIND_SUCCESS";
export const FETCH_FIND_FAILURE = "FETCH_FIND_FAILURE";

export const CREATE_FIND_REQUEST = "CREATE_FIND_REQUEST";
export const CREATE_FIND_SUCCESS = "CREATE_FIND_SUCCESS";
export const CREATE_FIND_FAILURE = "CREATE_FIND_FAILURE";

export const UPDATE_FIND_REQUEST = "UPDATE_FIND_REQUEST";
export const UPDATE_FIND_SUCCESS = "UPDATE_FIND_SUCCESS";
export const UPDATE_FIND_FAILURE = "UPDATE_FIND_FAILURE";

export const DELETE_FINDS_REQUEST = "DELETE_FINDS_REQUEST";
export const DELETE_FINDS_SUCCESS = "DELETE_FINDS_SUCCESS";
export const DELETE_FINDS_FAILURE = "DELETE_FINDS_FAILURE";