export const CREATE_REGISTER_REQUEST = "CREATE_REGISTER_REQUEST";
export const CREATE_REGISTER_SUCCESS = "CREATE_REGISTER_SUCCESS";
export const CREATE_REGISTER_FAILURE = "CREATE_REGISTER_FAILURE";

export const VERIFY_USERNAME_REQUEST = "VERIFY_USERNAME_REQUEST";
export const VERIFY_USERNAME_SUCCESS = "VERIFY_USERNAME_SUCCESS;";
export const VERIFY_USERNAME_FAILURE = "VERIFY_USERNAME_FAILURE";

export const SEND_TEL_VERIFICATION_REQUEST = "SEND_TEL_VERIFICATION_REQUEST"
export const SEND_TEL_VERIFICATION_SUCCESS = "SEND_TEL_VERIFICATION_SUCCESS"
export const SEND_TEL_VERIFICATION_FAILURE = "SEND_TEL_VERIFICATION_FAILURE"

export const VERIFY_TEL_NUMBER_REQUEST = "VERIFY_TEL_NUMBER_REQUEST"
export const VERIFY_TEL_NUMBER_SUCCESS = "VERIFY_TEL_NUMBER_SUCCESS"
export const VERIFY_TEL_NUMBER_FAILURE = "VERIFY_TEL_NUMBER_FAILURE"

export const SET_REGISTER_FORM = "SET_REGISTER_FORM";
export const RESET_REGISTER_FORM = "RESET_REGISTER_FORM";