export const FETCH_PREFERENCES_REQUEST = "FETCH_PREFERENCES_REQUEST";
export const FETCH_PREFERENCES_SUCCESS = "FETCH_PREFERENCES_SUCCESS";
export const FETCH_PREFERENCES_FAILURE = "FETCH_PREFERENCES_FAILURE";

export const FETCH_PREFERENCE_REQUEST = "FETCH_PREFERENCE_REQUEST";
export const FETCH_PREFERENCE_SUCCESS = "FETCH_PREFERENCE_SUCCESS";
export const FETCH_PREFERENCE_FAILURE = "FETCH_PREFERENCE_FAILURE";