export const FETCH_REGISTERS_REQUEST = "FETCH_REGISTERS_REQUEST";
export const FETCH_REGISTERS_SUCCESS = "FETCH_REGISTERS_SUCCESS";
export const FETCH_REGISTERS_FAILURE = "FETCH_REGISTERS_FAILURE";

export const FETCH_REGISTER_REQUEST = "FETCH_REGISTER_REQUEST";
export const FETCH_REGISTER_SUCCESS = "FETCH_REGISTER_SUCCESS";
export const FETCH_REGISTER_FAILURE = "FETCH_REGISTER_FAILURE";

export const CREATE_REGISTER_REQUEST = "CREATE_REGISTER_REQUEST";
export const CREATE_REGISTER_SUCCESS = "CREATE_REGISTER_SUCCESS";
export const CREATE_REGISTER_FAILURE = "CREATE_REGISTER_FAILURE";

export const UPDATE_REGISTER_REQUEST = "UPDATE_REGISTER_REQUEST";
export const UPDATE_REGISTER_SUCCESS = "UPDATE_REGISTER_SUCCESS";
export const UPDATE_REGISTER_FAILURE = "UPDATE_REGISTER_FAILURE";

export const DELETE_REGISTERS_REQUEST = "DELETE_REGISTERS_REQUEST";
export const DELETE_REGISTERS_SUCCESS = "DELETE_REGISTERS_SUCCESS";
export const DELETE_REGISTERS_FAILURE = "DELETE_REGISTERS_FAILURE";