export const FETCH_EXCHANGES_REQUEST = "FETCH_EXCHANGES_REQUEST";
export const FETCH_EXCHANGES_SUCCESS = "FETCH_EXCHANGES_SUCCESS";
export const FETCH_EXCHANGES_FAILURE = "FETCH_EXCHANGES_FAILURE";

export const FETCH_EXCHANGE_REQUEST = "FETCH_EXCHANGE_REQUEST";
export const FETCH_EXCHANGE_SUCCESS = "FETCH_EXCHANGE_SUCCESS";
export const FETCH_EXCHANGE_FAILURE = "FETCH_EXCHANGE_FAILURE";