export const FETCH_MESSAGES_REQUEST = "FETCH_MESSAGES_REQUEST";
export const FETCH_MESSAGES_SUCCESS = "FETCH_MESSAGES_SUCCESS";
export const FETCH_MESSAGES_FAILURE = "FETCH_MESSAGES_FAILURE";

export const FETCH_MESSAGE_REQUEST = "FETCH_MESSAGE_REQUEST";
export const FETCH_MESSAGE_SUCCESS = "FETCH_MESSAGE_SUCCESS";
export const FETCH_MESSAGE_FAILURE = "FETCH_MESSAGE_FAILURE";

export const CREATE_MESSAGE_REQUEST = "CREATE_MESSAGE_REQUEST";
export const CREATE_MESSAGE_SUCCESS = "CREATE_MESSAGE_SUCCESS";
export const CREATE_MESSAGE_FAILURE = "CREATE_MESSAGE_FAILURE";

export const UPDATE_MESSAGE_REQUEST = "UPDATE_MESSAGE_REQUEST";
export const UPDATE_MESSAGE_SUCCESS = "UPDATE_MESSAGE_SUCCESS";
export const UPDATE_MESSAGE_FAILURE = "UPDATE_MESSAGE_FAILURE";

export const DELETE_MESSAGES_REQUEST = "DELETE_MESSAGES_REQUEST";
export const DELETE_MESSAGES_SUCCESS = "DELETE_MESSAGES_SUCCESS";
export const DELETE_MESSAGES_FAILURE = "DELETE_MESSAGES_FAILURE";

export const MARKREAD_MESSAGE_REQUEST = "MARKREAD_MESSAGE_REQUEST";
export const MARKREAD_MESSAGE_SUCCESS = "MARKREAD_MESSAGE_SUCCESS";
export const MARKREAD_MESSAGE_FAILURE = "MARKREAD_MESSAGE_FAILURE";

export const SEARCH_ANY_WORD_MESSAGE = "SEARCH_ANY_WORD_MESSAGE";
export const SEARCH_HANDLE_CHANGE_MESSAGE = "SEARCH_HANDLE_CHANGE_MESSAGE";

export const SWITCH_TO_MESSAGELIST = "SWITCH_TO_MESSAGELIST";

//SORT LIST
export const DISPLAY_MESSAGE_WAITING_LIST = "DISPLAY_MESSAGE_WAITING_LIST";
export const DISPLAY_MESSAGE_NORMAL_LIST = "DISPLAY_MESSAGE_NORMAL_LIST";
export const DISPLAY_MESSAGE_BANNED_LIST = "DISPLAY_MESSAGE_BANNED_LIST";
export const DISPLAY_MESSAGE_WARNING_LIST = "DISPLAY_MESSAGE_WARNING_LIST";
export const DISPLAY_MESSAGE_DEBUGGING_LIST = "DISPLAY_MESSAGE_DEBUGGING_LIST";
export const DISPLAY_MESSAGE_ALL_LIST = "DISPLAY_MESSAGE_ALL_LIST";

//sort by categories
export const SORT_BY_MESSAGE_ID = "SORT_BY_MESSAGE_ID";
export const SORT_BY_MESSAGE_NICKNAME = "SORT_BY_MESSAGE_NICKNAME";
export const SORT_BY_MESSAGE_NAME = "SORT_BY_MESSAGE_NAME";
export const SORT_BY_MESSAGE_TITLE = "SORT_BY_MESSAGE_TITLE";
export const SORT_BY_MESSAGE_CONTENT = "SORT_BY_MESSAGE_CONTENT";
