export const FETCH_SWIPERMAINS_REQUEST = "FETCH_SWIPERMAINS_REQUEST";
export const FETCH_SWIPERMAINS_SUCCESS = "FETCH_SWIPERMAINS_SUCCESS";
export const FETCH_SWIPERMAINS_FAILURE = "FETCH_SWIPERMAINS_FAILURE";

export const FETCH_SWIPERMAIN_REQUEST = "FETCH_SWIPERMAIN_REQUEST";
export const FETCH_SWIPERMAIN_SUCCESS = "FETCH_SWIPERMAIN_SUCCESS";
export const FETCH_SWIPERMAIN_FAILURE = "FETCH_SWIPERMAIN_FAILURE";

export const CREATE_SWIPERMAIN_REQUEST = "CREATE_SWIPERMAIN_REQUEST";
export const CREATE_SWIPERMAIN_SUCCESS = "CREATE_SWIPERMAIN_SUCCESS";
export const CREATE_SWIPERMAIN_FAILURE = "CREATE_SWIPERMAIN_FAILURE";

export const UPDATE_SWIPERMAIN_REQUEST = "UPDATE_SWIPERMAIN_REQUEST";
export const UPDATE_SWIPERMAIN_SUCCESS = "UPDATE_SWIPERMAIN_SUCCESS";
export const UPDATE_SWIPERMAIN_FAILURE = "UPDATE_SWIPERMAIN_FAILURE";

export const DELETE_SWIPERMAINS_REQUEST = "DELETE_SWIPERMAINS_REQUEST";
export const DELETE_SWIPERMAINS_SUCCESS = "DELETE_SWIPERMAINS_SUCCESS";
export const DELETE_SWIPERMAINS_FAILURE = "DELETE_SWIPERMAINS_FAILURE";