export const FETCH_POINTS_REQUEST = "FETCH_POINTS_REQUEST";
export const FETCH_POINTS_SUCCESS = "FETCH_POINTS_SUCCESS";
export const FETCH_POINTS_FAILURE = "FETCH_POINTS_FAILURE";

export const FETCH_POINT_REQUEST = "FETCH_POINT_REQUEST";
export const FETCH_POINT_SUCCESS = "FETCH_POINT_SUCCESS";
export const FETCH_POINT_FAILURE = "FETCH_POINT_FAILURE";

export const CREATE_POINT_REQUEST = "FETCH_POINT_REQUEST";
export const CREATE_POINT_SUCCESS = "FETCH_POINT_SUCCESS";
export const CREATE_POINT_FAILURE = "FETCH_POINT_FAILURE";

export const DELETE_POINT_REQUEST = "FETCH_POINT_REQUEST";
export const DELETE_POINT_SUCCESS = "FETCH_POINT_SUCCESS";
export const DELETE_POINT_FAILURE = "FETCH_POINT_FAILURE";