export const FETCH_WITHDRAWALS_REQUEST = "FETCH_WITHDRAWALS_REQUEST";
export const FETCH_WITHDRAWALS_SUCCESS = "FETCH_WITHDRAWALS_SUCCESS";
export const FETCH_WITHDRAWALS_FAILURE = "FETCH_WITHDRAWALS_FAILURE";

export const FETCH_WITHDRAWAL_REQUEST = "FETCH_WITHDRAWAL_REQUEST";
export const FETCH_WITHDRAWAL_SUCCESS = "FETCH_WITHDRAWAL_SUCCESS";
export const FETCH_WITHDRAWAL_FAILURE = "FETCH_WITHDRAWAL_FAILURE";

export const CREATE_WITHDRAWAL_REQUEST = "CREATE_WITHDRAWAL_REQUEST";
export const CREATE_WITHDRAWAL_SUCCESS = "CREATE_WITHDRAWAL_SUCCESS";
export const CREATE_WITHDRAWAL_FAILURE = "CREATE_WITHDRAWAL_FAILURE";

export const UPDATE_WITHDRAWAL_REQUEST = "UPDATE_WITHDRAWAL_REQUEST";
export const UPDATE_WITHDRAWAL_SUCCESS = "UPDATE_WITHDRAWAL_SUCCESS";
export const UPDATE_WITHDRAWAL_FAILURE = "UPDATE_WITHDRAWAL_FAILURE";

export const DELETE_WITHDRAWALS_REQUEST = "DELETE_WITHDRAWALS_REQUEST";
export const DELETE_WITHDRAWALS_SUCCESS = "DELETE_WITHDRAWALS_SUCCESS";
export const DELETE_WITHDRAWALS_FAILURE = "DELETE_WITHDRAWALS_FAILURE";
export const OPEN_CREATE_MODAL = "OPEN_CREATE_MODAL";
export const CLOSE_CREATE_MODAL = "CLOSE_CREATE_MODAL";
export const CHANGE_WITHDRAWAL_CATEGORY = "CHANGE_WITHDRAWAL_CATEGORY";
export const CHANGE_WITHDRAWAL_AMOUNT = "CHANGE_WITHDRAWAL_AMOUNT";
export const CHANGE_WITHDRAWAL_IDS = "CHANGE_WITHDRAWAL_IDS";
export const FILTERED_PROCEEDING_LIST = "FILTERED_PROCEEDING_LIST";
export const FILTERED_HIT_LIST = "FILTERED_HIT_LIST";
export const FILTERED_AESTHETIC_LIST = "FILTERED_AESTHETIC_LIST";
export const LIST_OF_WITHDRAWAL = "LIST_OF_WITHDRAWAL";

export const CHECK_WITHDRAWAL_CERTAIN_ITEM = "CHECK_WITHDRAWAL_CERTAIN_ITEM";
export const CHECK_ALL_WITHDRAWALS = "CHECK_ALL_WITHDRAWALS";
export const LIST_OF_TODELETE_WITHDRAWALS = "LIST_OF_TODELETE_WITHDRAWALS";

export const SELECT_WITHDRAWAL_METHOD = "SELECT_WITHDRAWAL_METHOD";
export const CHANGE_CREATE_WITHDRAWAL_AMOUNT =
  "CHANGE_CREATE_WITHDRAWAL_AMOUNT";

export const INCREMENT_WITHDRAWAL_AMOUNT = "INCREMENT_WITHDRAWAL_AMOUNT";
export const DECREMENT_WITHDRAWAL_AMOUNT = "DECREMENT_WITHDRAWAL_AMOUNT";

export const ENTER_WITHDRAWAL_PASSWORD = "ENTER_WITHDRAWAL_PASSWORD";
export const RESET_CREATE_WITHDRAWAL = "RESET_CREATE_WITHDRAWAL";
