export const FETCH_BETTINGS_REQUEST = "FETCH_BETTINGS_REQUEST";
export const FETCH_BETTINGS_SUCCESS = "FETCH_BETTINGS_SUCCESS";
export const FETCH_BETTINGS_FAILURE = "FETCH_BETTINGS_FAILURE";

export const FETCH_BETTING_REQUEST = "FETCH_BETTING_REQUEST";
export const FETCH_BETTING_SUCCESS = "FETCH_BETTING_SUCCESS";
export const FETCH_BETTING_FAILURE = "FETCH_BETTING_FAILURE";