export const FETCH_PROMOS_REQUEST = "FETCH_PROMOS_REQUEST";
export const FETCH_PROMOS_SUCCESS = "FETCH_PROMOS_SUCCESS";
export const FETCH_PROMOS_FAILURE = "FETCH_PROMOS_FAILURE";

export const FETCH_PROMO_REQUEST = "FETCH_PROMO_REQUEST";
export const FETCH_PROMO_SUCCESS = "FETCH_PROMO_SUCCESS";
export const FETCH_PROMO_FAILURE = "FETCH_PROMO_FAILURE";