export const FETCH_NOTICES_REQUEST = "FETCH_NOTICES_REQUEST";
export const FETCH_NOTICES_SUCCESS = "FETCH_NOTICES_SUCCESS";
export const FETCH_NOTICES_FAILURE = "FETCH_NOTICES_FAILURE";

export const FETCH_NOTICE_REQUEST = "FETCH_NOTICE_REQUEST";
export const FETCH_NOTICE_SUCCESS = "FETCH_NOTICE_SUCCESS";
export const FETCH_NOTICE_FAILURE = "FETCH_NOTICE_FAILURE"; 