export const FETCH_MAINS_REQUEST = "FETCH_MAINS_REQUEST";
export const FETCH_MAINS_SUCCESS = "FETCH_MAINS_SUCCESS";
export const FETCH_MAINS_FAILURE = "FETCH_MAINS_FAILURE";

export const FETCH_MAIN_REQUEST = "FETCH_MAIN_REQUEST";
export const FETCH_MAIN_SUCCESS = "FETCH_MAIN_SUCCESS";
export const FETCH_MAIN_FAILURE = "FETCH_MAIN_FAILURE"; 

export const CREATE_MAIN_REQUEST = "CREATE_MAIN_REQUEST";
export const CREATE_MAIN_SUCCESS = "CREATE_MAIN_SUCCESS";
export const CREATE_MAIN_FAILURE = "CREATE_MAIN_FAILURE"; 

export const UPDATE_MAIN_REQUEST = "UPDATE_MAIN_REQUEST";
export const UPDATE_MAIN_SUCCESS = "UPDATE_MAIN_SUCCESS";
export const UPDATE_MAIN_FAILURE = "UPDATE_MAIN_FAILURE";

export const DELETE_MAINS_REQUEST = "DELETE_MAINS_REQUEST";
export const DELETE_MAINS_SUCCESS = "DELETE_MAINS_SUCCESS";
export const DELETE_MAINS_FAILURE = "DELETE_MAINS_FAILURE";