export const FETCH_ESPORTS_REQUEST = "FETCH_ESPORTS_REQUEST";
export const FETCH_ESPORTS_SUCCESS = "FETCH_ESPORTS_SUCCESS";
export const FETCH_ESPORTS_FAILURE = "FETCH_ESPORTS_FAILURE";

export const FETCH_ESPORT_REQUEST = "FETCH_ESPORT_REQUEST";
export const FETCH_ESPORT_SUCCESS = "FETCH_ESPORT_SUCCESS";
export const FETCH_ESPORT_FAILURE = "FETCH_ESPORT_FAILURE";

export const CREATE_ESPORT_REQUEST = "CREATE_ESPORT_REQUEST";
export const CREATE_ESPORT_SUCCESS = "CREATE_ESPORT_SUCCESS";
export const CREATE_ESPORT_FAILURE = "CREATE_ESPORT_FAILURE";

export const UPDATE_ESPORT_REQUEST = "UPDATE_ESPORT_REQUEST";
export const UPDATE_ESPORT_SUCCESS = "UPDATE_ESPORT_SUCCESS";
export const UPDATE_ESPORT_FAILURE = "UPDATE_ESPORT_FAILURE";

export const DELETE_ESPORTS_REQUEST = "DELETE_ESPORTS_REQUEST";
export const DELETE_ESPORTS_SUCCESS = "DELETE_ESPORTS_SUCCESS";
export const DELETE_ESPORTS_FAILURE = "DELETE_ESPORTS_FAILURE";


export const FETCH_INPLAY = "FETCH_INPLAY";
export const FETCH_PREMATCH = "FETCH_PREMATCH";
