export const FETCH_NOTICES_REQUEST = "FETCH_NOTICES_REQUEST";
export const FETCH_NOTICES_SUCCESS = "FETCH_NOTICES_SUCCESS";
export const FETCH_NOTICES_FAILURE = "FETCH_NOTICES_FAILURE";

export const FETCH_NOTICE_REQUEST = "FETCH_NOTICE_REQUEST";
export const FETCH_NOTICE_SUCCESS = "FETCH_NOTICE_SUCCESS";
export const FETCH_NOTICE_FAILURE = "FETCH_NOTICE_FAILURE";

export const CREATE_NOTICE_REQUEST = "CREATE_NOTICE_REQUEST";
export const CREATE_NOTICE_SUCCESS = "CREATE_NOTICE_SUCCESS";
export const CREATE_NOTICE_FAILURE = "CREATE_NOTICE_FAILURE";

export const UPDATE_NOTICE_REQUEST = "UPDATE_NOTICE_REQUEST";
export const UPDATE_NOTICE_SUCCESS = "UPDATE_NOTICE_SUCCESS";
export const UPDATE_NOTICE_FAILURE = "UPDATE_NOTICE_FAILURE";

export const DELETE_NOTICES_REQUEST = "DELETE_NOTICES_REQUEST";
export const DELETE_NOTICES_SUCCESS = "DELETE_NOTICES_SUCCESS";
export const DELETE_NOTICES_FAILURE = "DELETE_NOTICES_FAILURE";
export const OPEN_CREATE_MODAL = "OPEN_CREATE_MODAL";
export const CLOSE_CREATE_MODAL = "CLOSE_CREATE_MODAL";
export const CHANGE_NOTICE_CATEGORY = "CHANGE_NOTICE_CATEGORY";
export const CHANGE_NOTICE_AMOUNT = "CHANGE_NOTICE_AMOUNT";
export const CHANGE_NOTICE_IDS = "CHANGE_NOTICE_IDS";
export const FILTERED_PROCEEDING_LIST = "FILTERED_PROCEEDING_LIST";
export const FILTERED_HIT_LIST = "FILTERED_HIT_LIST";
export const FILTERED_AESTHETIC_LIST = "FILTERED_AESTHETIC_LIST";
export const LIST_OF_NOTICE = "LIST_OF_NOTICE";

export const CHECK_NOTICE_CERTAIN_ITEM = "CHECK_NOTICE_CERTAIN_ITEM";
export const LIST_OF_TODELETE_NOTICES = "LIST_OF_TODELETE_NOTICES";

export const SELECT_NOTICE_METHOD = "SELECT_NOTICE_METHOD";
export const CHANGE_CREATE_NOTICE_AMOUNT = "CHANGE_CREATE_NOTICE_AMOUNT";

export const INCREMENT_NOTICE_AMOUNT = "INCREMENT_DEPOSIT_AMOUNT";
export const DECREMENT_NOTICE_AMOUNT = "DECREMENT_DEPOSIT_AMOUNT";

export const FROM_CASH_TO_CASINO_NOTICE = "FROM_CASH_TO_CASINO_NOTICE";
export const FROM_CASINO_TO_CASH_NOTICE = "FROM_CASINO_TO_CASH_NOTICE";

export const RESET_CREATE_NOTICE = "RESET_CREATE_NOTICE";
export const CHECK_ALL_NOTICE = "CHECK_ALL_NOTICE";

export const CHANGE_NOTICE_TITLE = "CHANGE_NOTICE_TITLE";
export const CHANGE_NOTICE_CONTENT = "CHANGE_NOTICE_CONTENT";

export const VIEW_NOTICE_ITEM = "VIEW_NOTICE_ITEM";


export const ONCLICK_PAGE_NOTICE = "ONCLICK_PAGE_NOTICE";
export const NEXT_PAGE_NOTICE = "NEXT_PAGE_NOTICE";
export const PREV_PAGE_NOTICE = "PREV_PAGE_NOTICE";
export const CHANGE_NOTICE_PAGE = "CHANGE_NOTICE_PAGE";
export const SET_NOTICE_PAGE = "SET_NOTICE_PAGE";