
export const SET_BET_OUTCOMES = "SET_BET_OUTCOMES";
export const SET_BET_AMOUNT = "SET_BET_AMOUNT";
export const SPLICE_OUTCOME = "SPLICE_OUTCOME";
export const RESET_OUTCOME = "RESET_OUTCOME";

export const BET_CHECK = "BET_CHECK";
export const BET_REQUEST = "BET_REQUEST";
export const BET_SUCCESS = "BET_SUCCESS";
export const BET_FAILURE = "BET_FAILURE";
export const SET_WS_BETSLIP = "SET_WS_BETSLIP";
export const RESET_LOADING_BET = "RESET_LOADING_BET";
