export const FETCH_INQUIRIES_REQUEST = "FETCH_INQUIRIES_REQUEST";
export const FETCH_INQUIRIES_SUCCESS = "FETCH_INQUIRIES_SUCCESS";
export const FETCH_INQUIRIES_FAILURE = "FETCH_INQUIRIES_FAILURE";

export const FETCH_INQUIRY_REQUEST = "FETCH_INQUIRY_REQUEST";
export const FETCH_INQUIRY_SUCCESS = "FETCH_INQUIRY_SUCCESS";
export const FETCH_INQUIRY_FAILURE = "FETCH_INQUIRY_FAILURE";

export const CREATE_INQUIRY_REQUEST = "CREATE_INQUIRY_REQUEST";
export const CREATE_INQUIRY_SUCCESS = "CREATE_INQUIRY_SUCCESS";
export const CREATE_INQUIRY_FAILURE = "CREATE_INQUIRY_FAILURE";

export const UPDATE_INQUIRY_REQUEST = "UPDATE_INQUIRY_REQUEST";
export const UPDATE_INQUIRY_SUCCESS = "UPDATE_INQUIRY_SUCCESS";
export const UPDATE_INQUIRY_FAILURE = "UPDATE_INQUIRY_FAILURE";

export const DELETE_INQUIRIES_REQUEST = "DELETE_INQUIRIES_REQUEST";
export const DELETE_INQUIRIES_SUCCESS = "DELETE_INQUIRIES_SUCCESS";
export const DELETE_INQUIRIES_FAILURE = "DELETE_INQUIRIES_FAILURE";
export const OPEN_CREATE_MODAL = "OPEN_CREATE_MODAL";
export const CLOSE_CREATE_MODAL = "CLOSE_CREATE_MODAL";
export const CHANGE_INQUIRY_CATEGORY = "CHANGE_INQUIRY_CATEGORY";
export const CHANGE_INQUIRY_AMOUNT = "CHANGE_INQUIRY_AMOUNT";
export const CHANGE_INQUIRY_IDS = "CHANGE_INQUIRY_IDS";
export const FILTERED_PROCEEDING_LIST = "FILTERED_PROCEEDING_LIST";
export const FILTERED_HIT_LIST = "FILTERED_HIT_LIST";
export const FILTERED_AESTHETIC_LIST = "FILTERED_AESTHETIC_LIST";
export const LIST_OF_INQUIRY = "LIST_OF_INQUIRY";

export const CHECK_INQUIRY_CERTAIN_ITEM = "CHECK_INQUIRY_CERTAIN_ITEM";
export const LIST_OF_TODELETE_INQUIRIES = "LIST_OF_TODELETE_INQUIRIES";

export const SELECT_INQUIRY_METHOD = "SELECT_INQUIRY_METHOD";
export const CHANGE_CREATE_INQUIRY_AMOUNT = "CHANGE_CREATE_INQUIRY_AMOUNT";

export const INCREMENT_INQUIRY_AMOUNT = "INCREMENT_DEPOSIT_AMOUNT";
export const DECREMENT_INQUIRY_AMOUNT = "DECREMENT_DEPOSIT_AMOUNT";

export const FROM_CASH_TO_CASINO_INQUIRY = "FROM_CASH_TO_CASINO_INQUIRY";
export const FROM_CASINO_TO_CASH_INQUIRY = "FROM_CASINO_TO_CASH_INQUIRY";

export const RESET_CREATE_INQUIRY = "RESET_CREATE_INQUIRY";
export const CHECK_ALL_INQUIRY = "CHECK_ALL_INQUIRY";

export const CHANGE_INQUIRY_TITLE = "CHANGE_INQUIRY_TITLE";
export const CHANGE_INQUIRY_CONTENT = "CHANGE_INQUIRY_CONTENT";

export const ONCLICK_PAGE_INQUIRY = "ONCLICK_PAGE_INQUIRY";
export const NEXT_PAGE_INQUIRY = "NEXT_PAGE_INQUIRY";
export const PREV_PAGE_INQUIRY = "PREV_PAGE_INQUIRY";
export const CHANGE_INQUIRY_PAGE = "CHANGE_INQUIRY_PAGE";
export const SET_INQUIRY_PAGE = "SET_INQUIRY_PAGE";
