export const FETCH_POSITIONS_REQUEST = "FETCH_POSITIONS_REQUEST";
export const FETCH_POSITIONS_SUCCESS = "FETCH_POSITIONS_SUCCESS";
export const FETCH_POSITIONS_FAILURE = "FETCH_POSITIONS_FAILURE";

export const FETCH_POSITION_REQUEST = "FETCH_POSITION_REQUEST";
export const FETCH_POSITION_SUCCESS = "FETCH_POSITION_SUCCESS";
export const FETCH_POSITION_FAILURE = "FETCH_POSITION_FAILURE";

export const CREATE_POSITION_REQUEST = "CREATE_POSITION_REQUEST";
export const CREATE_POSITION_SUCCESS = "CREATE_POSITION_SUCCESS";
export const CREATE_POSITION_FAILURE = "CREATE_POSITION_FAILURE";

export const UPDATE_POSITION_REQUEST = "UPDATE_POSITION_REQUEST";
export const UPDATE_POSITION_SUCCESS = "UPDATE_POSITION_SUCCESS";
export const UPDATE_POSITION_FAILURE = "UPDATE_POSITION_FAILURE";

export const SELECT_POSITION = "SELECT_POSITION";


export const DELETE_POSITIONS_REQUEST = "DELETE_POSITIONS_REQUEST";
export const DELETE_POSITIONS_SUCCESS = "DELETE_POSITIONS_SUCCESS";
export const DELETE_POSITIONS_FAILURE = "DELETE_POSITIONS_FAILURE";
export const OPEN_CREATE_MODAL = "OPEN_CREATE_MODAL";
export const CLOSE_CREATE_MODAL = "CLOSE_CREATE_MODAL";
export const CHANGE_POSITION_CATEGORY = "CHANGE_POSITION_CATEGORY";
export const CHANGE_POSITION_AMOUNT = "CHANGE_POSITION_AMOUNT";
export const CHANGE_POSITION_IDS = "CHANGE_POSITION_IDS";
export const FILTERED_PROCEEDING_LIST = "FILTERED_PROCEEDING_LIST";
export const FILTERED_HIT_LIST = "FILTERED_HIT_LIST";
export const FILTERED_AESTHETIC_LIST = "FILTERED_AESTHETIC_LIST";
export const LIST_OF_POSITION = "LIST_OF_POSITION";

export const SELECT_ALL_POSITION = "SELECT_ALL_POSITION";

export const ONCLICK_PAGE_POSITION = "ONCLICK_PAGE_POSITION";
export const NEXT_PAGE_POSITION = "NEXT_PAGE_POSITION";
export const PREV_PAGE_POSITION = "PREV_PAGE_POSITION";
export const CHANGE_POSITION_PAGE = "CHANGE_POSITION_PAGE";
export const SET_POSITION_PAGE = "SET_POSITION_PAGE";
export const CHECK_POSITION_CERTAIN_ITEM = "CHECK_POSITION_CERTAIN_ITEM";

export const CHANGE_POSITION_STATUS = "CHANGE_POSITION_STATUS";
