export const FETCH_DEPOSITS_REQUEST = "FETCH_DEPOSITS_REQUEST";
export const FETCH_DEPOSITS_SUCCESS = "FETCH_DEPOSITS_SUCCESS";
export const FETCH_DEPOSITS_FAILURE = "FETCH_DEPOSITS_FAILURE";

export const FETCH_DEPOSIT_REQUEST = "FETCH_DEPOSIT_REQUEST";
export const FETCH_DEPOSIT_SUCCESS = "FETCH_DEPOSIT_SUCCESS";
export const FETCH_DEPOSIT_FAILURE = "FETCH_DEPOSIT_FAILURE";

export const CREATE_DEPOSIT_REQUEST = "CREATE_DEPOSIT_REQUEST";
export const CREATE_DEPOSIT_SUCCESS = "CREATE_DEPOSIT_SUCCESS";
export const CREATE_DEPOSIT_FAILURE = "CREATE_DEPOSIT_FAILURE";

export const UPDATE_DEPOSIT_REQUEST = "UPDATE_DEPOSIT_REQUEST";
export const UPDATE_DEPOSIT_SUCCESS = "UPDATE_DEPOSIT_SUCCESS";
export const UPDATE_DEPOSIT_FAILURE = "UPDATE_DEPOSIT_FAILURE";

export const DELETE_DEPOSITS_REQUEST = "DELETE_DEPOSITS_REQUEST";
export const DELETE_DEPOSITS_SUCCESS = "DELETE_DEPOSITS_SUCCESS";
export const DELETE_DEPOSITS_FAILURE = "DELETE_DEPOSITS_FAILURE";
export const OPEN_CREATE_MODAL = "OPEN_CREATE_MODAL";
export const CLOSE_CREATE_MODAL = "CLOSE_CREATE_MODAL";
export const CHANGE_DEPOSIT_CATEGORY = "CHANGE_DEPOSIT_CATEGORY";
export const CHANGE_DEPOSIT_AMOUNT = "CHANGE_DEPOSIT_AMOUNT";
export const CHANGE_DEPOSIT_IDS = "CHANGE_DEPOSIT_IDS";
export const FILTERED_PROCEEDING_LIST = "FILTERED_PROCEEDING_LIST";
export const FILTERED_HIT_LIST = "FILTERED_HIT_LIST";
export const FILTERED_AESTHETIC_LIST = "FILTERED_AESTHETIC_LIST";
export const LIST_OF_DEPOSIT = "LIST_OF_DEPOSIT";

export const CHECK_DEPOSIT_CERTAIN_ITEM = "CHECK_DEPOSIT_CERTAIN_ITEM";
export const LIST_OF_TODELETE_DEPOSITS = "LIST_OF_TODELETE_DEPOSITS";

export const SELECT_DEPOSIT_METHOD = "SELECT_DEPOSIT_METHOD";
export const CHANGE_CREATE_DEPOSIT_AMOUNT = "CHANGE_CREATE_DEPOSIT_AMOUNT";

export const INCREMENT_DEPOSIT_AMOUNT = "INCREMENT_DEPOSIT_AMOUNT";
export const DECREMENT_DEPOSIT_AMOUNT = "DECREMENT_DEPOSIT_AMOUNT";

export const RESET_CREATE_DEPOSIT = "RESET_CREATE_DEPOSIT";
export const CHECK_ALL_DEPOSIT = "CHECK_ALL_DEPOSIT";

export const SET_DEPOSIT_PAGE = "SET_DEPOSIT_PAGE";
export const DEPOSITPREVPAGE = "DEPOSITPREVPAGE";
export const DEPOSITNEXTPAGE = "DEPOSITNEXTPAGE";
export const DEPOSIT_PAGINATION_REQUEST_DATA =
  "DEPOSIT_PAGINATION_REQUEST_DATA";

export const PAGINATION_REQUEST_DEPOSIT = "PAGINATION_REQUEST_DEPOSIT";
export const PAGINATION_SUCCESS_DEPOSIT = "PAGINATION_SUCCESS_DEPOSIT";
export const PAGINATION_FAILURE_DEPOSIT = "PAGINATION_FAILURE_DEPOSIT";

export const ONCLICK_PAGE_DEPOSIT = "ONCLICK_PAGE_DEPOSIT";
export const NEXT_PAGE_DEPOSIT = "NEXT_PAGE_DEPOSIT";
export const PREV_PAGE_DEPOSIT = "PREV_PAGE_DEPOSIT";
