export const FETCH_PRESETS_REQUEST = "FETCH_PRESETS_REQUEST";
export const FETCH_PRESETS_SUCCESS = "FETCH_PRESETS_SUCCESS";
export const FETCH_PRESETS_FAILURE = "FETCH_PRESETS_FAILURE";

export const FETCH_PRESET_REQUEST = "FETCH_PRESET_REQUEST";
export const FETCH_PRESET_SUCCESS = "FETCH_PRESET_SUCCESS";
export const FETCH_PRESET_FAILURE = "FETCH_PRESET_FAILURE";