export const FETCH_CASHES_REQUEST = "FETCH_CASHES_REQUEST";
export const FETCH_CASHES_SUCCESS = "FETCH_CASHES_SUCCESS";
export const FETCH_CASHES_FAILURE = "FETCH_CASHES_FAILURE";

export const FETCH_CASH_REQUEST = "FETCH_CASH_REQUEST";
export const FETCH_CASH_SUCCESS = "FETCH_CASH_SUCCESS";
export const FETCH_CASH_FAILURE = "FETCH_CASH_FAILURE";