export const FETCH_INPLAYS_REQUEST = "FETCH_INPLAYS_REQUEST";
export const FETCH_INPLAYS_SUCCESS = "FETCH_INPLAYS_SUCCESS";
export const FETCH_INPLAYS_FAILURE = "FETCH_INPLAYS_FAILURE";

export const FETCH_INPLAY_REQUEST = "FETCH_INPLAY_REQUEST";
export const FETCH_INPLAY_SUCCESS = "FETCH_INPLAY_SUCCESS";
export const FETCH_INPLAY_FAILURE = "FETCH_INPLAY_FAILURE";

export const GET_INPLAYDETAILS = "GET_INPLAYDETAILS";
export const SET_MARKETS = "SET_MARKETS";

export const FETCH_MARKET_PER_MATCHES_SUCCESS_INPLAY = "FETCH_MARKET_PER_MATCHES_SUCCESS_INPLAY";
export const FETCH_MARKET_PER_MATCHES_FAILURE_INPLAY = "FETCH_MARKET_PER_MATCHES_FAILURE_INPLAY";


export const SET_WS_MARKETS_INPLAY = "SET_WS_MARKETS_INPLAY";



