export const FETCH_INPLAYS_REQUEST = "FETCH_INPLAYS_REQUEST";
export const FETCH_INPLAYS_SUCCESS = "FETCH_INPLAYS_SUCCESS";
export const FETCH_INPLAYS_FAILURE = "FETCH_INPLAYS_FAILURE";

export const FETCH_INPLAY_REQUEST = "FETCH_INPLAY_REQUEST";
export const FETCH_INPLAY_SUCCESS = "FETCH_INPLAY_SUCCESS";
export const FETCH_INPLAY_FAILURE = "FETCH_INPLAY_FAILURE";

export const CREATE_INPLAY_REQUEST = "CREATE_INPLAY_REQUEST";
export const CREATE_INPLAY_SUCCESS = "CREATE_INPLAY_SUCCESS";
export const CREATE_INPLAY_FAILURE = "CREATE_INPLAY_FAILURE";

export const UPDATE_INPLAY_REQUEST = "UPDATE_INPLAY_REQUEST";
export const UPDATE_INPLAY_SUCCESS = "UPDATE_INPLAY_SUCCESS";
export const UPDATE_INPLAY_FAILURE = "UPDATE_INPLAY_FAILURE";

export const DELETE_INPLAYS_REQUEST = "DELETE_INPLAYS_REQUEST";
export const DELETE_INPLAYS_SUCCESS = "DELETE_INPLAYS_SUCCESS";
export const DELETE_INPLAYS_FAILURE = "DELETE_INPLAYS_FAILURE";