export const FETCH_EXCHANGES_REQUEST = "FETCH_EXCHANGES_REQUEST";
export const FETCH_EXCHANGES_SUCCESS = "FETCH_EXCHANGES_SUCCESS";
export const FETCH_EXCHANGES_FAILURE = "FETCH_EXCHANGES_FAILURE";

export const FETCH_EXCHANGE_REQUEST = "FETCH_EXCHANGE_REQUEST";
export const FETCH_EXCHANGE_SUCCESS = "FETCH_EXCHANGE_SUCCESS";
export const FETCH_EXCHANGE_FAILURE = "FETCH_EXCHANGE_FAILURE";

export const CREATE_EXCHANGE_REQUEST = "CREATE_EXCHANGE_REQUEST";
export const CREATE_EXCHANGE_SUCCESS = "CREATE_EXCHANGE_SUCCESS";
export const CREATE_EXCHANGE_FAILURE = "CREATE_EXCHANGE_FAILURE";

export const UPDATE_EXCHANGE_REQUEST = "UPDATE_EXCHANGE_REQUEST";
export const UPDATE_EXCHANGE_SUCCESS = "UPDATE_EXCHANGE_SUCCESS";
export const UPDATE_EXCHANGE_FAILURE = "UPDATE_EXCHANGE_FAILURE";

export const DELETE_EXCHANGES_REQUEST = "DELETE_EXCHANGES_REQUEST";
export const DELETE_EXCHANGES_SUCCESS = "DELETE_EXCHANGES_SUCCESS";
export const DELETE_EXCHANGES_FAILURE = "DELETE_EXCHANGES_FAILURE";

export const OPEN_CREATE_MODAL = "OPEN_CREATE_MODAL";
export const CLOSE_CREATE_MODAL = "CLOSE_CREATE_MODAL";
export const CHANGE_EXCHANGE_CATEGORY = "CHANGE_EXCHANGE_CATEGORY";
export const CHANGE_EXCHANGE_AMOUNT = "CHANGE_EXCHANGE_AMOUNT";
export const CHANGE_EXCHANGE_IDS = "CHANGE_EXCHANGE_IDS";
export const FILTERED_PROCEEDING_LIST = "FILTERED_PROCEEDING_LIST";
export const FILTERED_HIT_LIST = "FILTERED_HIT_LIST";
export const FILTERED_AESTHETIC_LIST = "FILTERED_AESTHETIC_LIST";
export const LIST_OF_EXCHANGE = "LIST_OF_EXCHANGE";

export const CHECK_EXCHANGE_CERTAIN_ITEM = "CHECK_EXCHANGE_CERTAIN_ITEM";
export const LIST_OF_TODELETE_EXCHANGES = "LIST_OF_TODELETE_EXCHANGES";

export const SELECT_EXCHANGE_METHOD = "SELECT_EXCHANGE_METHOD";
export const CHANGE_CREATE_EXCHANGE_AMOUNT = "CHANGE_CREATE_EXCHANGE_AMOUNT";

export const INCREMENT_EXCHANGE_AMOUNT = "INCREMENT_DEPOSIT_AMOUNT";
export const DECREMENT_EXCHANGE_AMOUNT = "DECREMENT_DEPOSIT_AMOUNT";

export const FROM_CASH_TO_CASINO_EXCHANGE = "FROM_CASH_TO_CASINO_EXCHANGE";
export const FROM_CASINO_TO_CASH_EXCHANGE = "FROM_CASINO_TO_CASH_EXCHANGE";

export const RESET_CREATE_EXCHANGE = "RESET_CREATE_EXCHANGE";
export const CHECK_ALL_EXCHANGE = "CHECK_ALL_EXCHANGE";
