export const FETCH_ESPORTSLIVES_REQUEST = "FETCH_ESPORTSLIVES_REQUEST";
export const FETCH_ESPORTSLIVES_SUCCESS = "FETCH_ESPORTSLIVES_SUCCESS";
export const FETCH_ESPORTSLIVES_FAILURE = "FETCH_ESPORTSLIVES_FAILURE";

export const FETCH_ESPORTSLIVE_REQUEST = "FETCH_ESPORTSLIVE_SLIVEREQUEST";
export const FETCH_ESPORTSLIVE_SUCCESS = "FETCH_ESPORTSLIVE_SLIVESUCCESS";
export const FETCH_ESPORTSLIVE_FAILURE = "FETCH_ESPORTSLIVE_SLIVEFAILURE";

export const CREATE_ESPORTSLIVE_REQUEST = "CREATE_ESPORTSLIVE_REQUEST";
export const CREATE_ESPORTSLIVE_SUCCESS = "CREATE_ESPORTSLIVE_SUCCESS";
export const CREATE_ESPORTSLIVE_FAILURE = "CREATE_ESPORTSLIVE_FAILURE";

export const UPDATE_ESPORTSLIVE_REQUEST = "UPDATE_ESPORTSLIVE_REQUEST";
export const UPDATE_ESPORTSLIVE_SUCCESS = "UPDATE_ESPORTSLIVE_SUCCESS";
export const UPDATE_ESPORTSLIVE_FAILURE = "UPDATE_ESPORTSLIVE_FAILURE";

export const DELETE_ESPORTSLIVES_REQUEST = "DELETE_ESPORTS_REQUEST";
export const DELETE_ESPORTSLIVES_SUCCESS = "DELETE_ESPORTS_SUCCESS";
export const DELETE_ESPORTSLIVES_FAILURE = "DELETE_ESPORTS_FAILURE";