export const FETCH_MAINS_REQUEST = "FETCH_MAINS_REQUEST";
export const FETCH_MAINS_SUCCESS = "FETCH_MAINS_SUCCESS";
export const FETCH_MAINS_FAILURE = "FETCH_MAINS_FAILURE";

export const FETCH_MAIN_REQUEST = "FETCH_MAIN_REQUEST";
export const FETCH_MAIN_SUCCESS = "FETCH_MAIN_SUCCESS";
export const FETCH_MAIN_FAILURE = "FETCH_MAIN_FAILURE";