export const FETCH_INPLAYDETAILS_REQUEST = "FETCH_INPLAYDETAILS_REQUEST";
export const FETCH_INPLAYDETAILS_SUCCESS = "FETCH_INPLAYDETAILS_SUCCESS";
export const FETCH_INPLAYDETAILS_FAILURE = "FETCH_INPLAYDETAILS_FAILURE";

export const FETCH_INPLAYDETAIL_REQUEST = "FETCH_INPLAYDETAIL_REQUEST";
export const FETCH_INPLAYDETAIL_SUCCESS = "FETCH_INPLAYDETAIL_SUCCESS";
export const FETCH_INPLAYDETAIL_FAILURE = "FETCH_INPLAYDETAIL_FAILURE";

export const CREATE_INPLAYDETAIL_REQUEST = "CREATE_INPLAYDETAIL_REQUEST";
export const CREATE_INPLAYDETAIL_SUCCESS = "CREATE_INPLAYDETAIL_SUCCESS";
export const CREATE_INPLAYDETAIL_FAILURE = "CREATE_INPLAYDETAIL_FAILURE";

export const UPDATE_INPLAYDETAIL_REQUEST = "UPDATE_INPLAYDETAIL_REQUEST";
export const UPDATE_INPLAYDETAIL_SUCCESS = "UPDATE_INPLAYDETAIL_SUCCESS";
export const UPDATE_INPLAYDETAIL_FAILURE = "UPDATE_INPLAYDETAIL_FAILURE";

export const DELETE_INPLAYDETAILS_REQUEST = "DELETE_INPLAYDETAILS_REQUEST";
export const DELETE_INPLAYDETAILS_SUCCESS = "DELETE_INPLAYDETAILS_SUCCESS";
export const DELETE_INPLAYDETAILS_FAILURE = "DELETE_INPLAYDETAILS_FAILURE";