export const SET_USER = "SET_USER";
export const SET_ACCESS_TOKEN = "SET_ACCESS_TOKEN";
export const SET_LOGOUT = "SET_LOGOUT";
export const SET_USER_STATUS = "SET_USER_STATUS";

export const FETCH_USERS_REQUEST = "FETCH_USERS_REQUEST";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAILURE = "FETCH_USERS_FAILURE";

export const REGISTRATION_FORM = "REGISTRATION_FORM";
export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILURE = "REGISTER_USER_FAILURE";




// export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
// export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
// export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";

// export const FETCH_USERS_REQUEST = "FETCH_USERS_REQUEST";
// export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
// export const FETCH_USERS_FAILURE = "FETCH_USERS_FAILURE";

// export const FETCH_USER_REQUEST = "FETCH_USER_REQUEST";
// export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
// export const FETCH_USER_FAILURE = "FETCH_USER_FAILURE";

// export const CREATE_USER_REQUEST = "CREATE_USER_REQUEST";
// export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
// export const CREATE_USER_FAILURE = "CREATE_USER_FAILURE";

// export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
// export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
// export const UPDATE_USER_FAILURE = "UPDATE_USER_FAILURE";

// export const DELETE_USERS_REQUEST = "DELETE_USERS_REQUEST";
// export const DELETE_USERS_SUCCESS = "DELETE_USERS_SUCCESS";
// export const DELETE_USERS_FAILURE = "DELETE_USERS_FAILURE";

export const CHANGE_USER_NEWPASSWORD = "CHANGE_USER_CURRENTPASSWORD";
export const CHANGE_USER_PASSCONFIRMATION = "CHANGE_USER_PASSCONFIRMATION";
export const HANDLE_USER_OLDPASSWORD = "HANDLE_USER_OLDPASSWORD";

export const CHANGE_PASSWORD_REQUEST = "CHANGE_PASSWORD_REQUEST";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAILURE = "CHANGE_PASSWORD_FAILURE";
