export const FETCH_SPORTS_REQUEST = "FETCH_SPORTS_REQUEST";
export const FETCH_SPORTS_SUCCESS = "FETCH_SPORTS_SUCCESS";
export const FETCH_SPORTS_FAILURE = "FETCH_SPORTS_FAILURE";

export const FETCH_SPORT_REQUEST = "FETCH_SPORT_REQUEST";
export const FETCH_SPORT_SUCCESS = "FETCH_SPORT_SUCCESS";
export const FETCH_SPORT_FAILURE = "FETCH_SPORT_FAILURE";

export const CREATE_SPORT_REQUEST = "CREATE_SPORT_REQUEST";
export const CREATE_SPORT_SUCCESS = "CREATE_SPORT_SUCCESS";
export const CREATE_SPORT_FAILURE = "CREATE_SPORT_FAILURE";

export const UPDATE_SPORT_REQUEST = "UPDATE_SPORT_REQUEST";
export const UPDATE_SPORT_SUCCESS = "UPDATE_SPORT_SUCCESS";
export const UPDATE_SPORT_FAILURE = "UPDATE_SPORT_FAILURE";

export const DELETE_SPORTS_REQUEST = "DELETE_SPORTS_REQUEST";
export const DELETE_SPORTS_SUCCESS = "DELETE_SPORTS_SUCCESS";
export const DELETE_SPORTS_FAILURE = "DELETE_SPORTS_FAILURE";