export const FETCH_MATCHES_SUCCESS = "FETCH_MATCHES_SUCCESS";
export const FETCH_MATCHES_FAILURE = "FETCH_MATCHES_FAILURE";

export const FETCH_TOURNAMENTS_SUCCESS = "FETCH_TOURNAMENTS_SUCCESS";
export const FETCH_TOURNAMENTS_FAILURE = "FETCH_TOURNAMENTS_FAILURE";

export const FETCH_COMPETITORS_SUCCESS = "FETCH_COMPETITORS_SUCCESS";
export const FETCH_COMPETITORS_FAILURE = "FETCH_COMPETITORS_FAILURE";

export const FETCH_OUTCOMES_SUCCESS = "FETCH_OUTCOMES_SUCCESS";
export const FETCH_OUTCOMES_FAILURE = "FETCH_OUTCOMES_FAILURE";

export const FETCH_MARKETS_SUCCESS = "FETCH_MARKETS_SUCCESS";
export const FETCH_MARKETS_FAILURE = "FETCH_MARKETS_FAILURE";

export const FETCH_SPORTS_SUCCESS = "FETCH_SPORTS_SUCCESS";
export const FETCH_SPORTS_FAILURE = "FETCH_SPORTS_FAILURE";

export const FETCH_MARKET_PER_MATCHES_SUCCESS = "FETCH_MARKET_PER_MATCHES_SUCCESS";
export const FETCH_MARKET_PER_MATCHES_FAILURE = "FETCH_MARKET_PER_MATCHES_FAILURE";









