export const FETCH_SUMMARIES_REQUEST = "FETCH_SUMMARIES_REQUEST";
export const FETCH_SUMMARIES_SUCCESS = "FETCH_SUMMARIES_SUCCESS";
export const FETCH_SUMMARIES_FAILURE = "FETCH_SUMMARIES_FAILURE";

export const FETCH_SUMMARY_REQUEST = "FETCH_SUMMARY_REQUEST";
export const FETCH_SUMMARY_SUCCESS = "FETCH_SUMMARY_SUCCESS";
export const FETCH_SUMMARY_FAILURE = "FETCH_SUMMARY_FAILURE"; 

export const CREATE_SUMMARY_REQUEST = "CREATE_SUMMARY_REQUEST";
export const CREATE_SUMMARY_SUCCESS = "CREATE_SUMMARY_SUCCESS";
export const CREATE_SUMMARY_FAILURE = "CREATE_SUMMARY_FAILURE"; 

export const UPDATE_SUMMARY_REQUEST = "UPDATE_SUMMARY_REQUEST";
export const UPDATE_SUMMARY_SUCCESS = "UPDATE_SUMMARY_SUCCESS";
export const UPDATE_SUMMARY_FAILURE = "UPDATE_SUMMARY_FAILURE";

export const DELETE_SUMMARIES_REQUEST = "DELETE_SUMMARIES_REQUEST";
export const DELETE_SUMMARIES_SUCCESS = "DELETE_SUMMARIES_SUCCESS";
export const DELETE_SUMMARIES_FAILURE = "DELETE_SUMMARIES_FAILURE";