export const FETCH_CASINOS_REQUEST = "FETCH_CASINOS_REQUEST";
export const FETCH_CASINOS_SUCCESS = "FETCH_CASINOS_SUCCESS";
export const FETCH_CASINOS_FAILURE = "FETCH_CASINOS_FAILURE";

export const FETCH_CASINO_REQUEST = "FETCH_CASINO_REQUEST";
export const FETCH_CASINO_SUCCESS = "FETCH_CASINO_SUCCESS";
export const FETCH_CASINO_FAILURE = "FETCH_CASINO_FAILURE";

export const CREATE_CASINO_REQUEST = "CREATE_CASINO_REQUEST";
export const CREATE_CASINO_SUCCESS = "CREATE_CASINO_SUCCESS";
export const CREATE_CASINO_FAILURE = "CREATE_CASINO_FAILURE";

export const UPDATE_CASINO_REQUEST = "UPDATE_CASINO_REQUEST";
export const UPDATE_CASINO_SUCCESS = "UPDATE_CASINO_SUCCESS";
export const UPDATE_CASINO_FAILURE = "UPDATE_CASINO_FAILURE";

export const DELETE_CASINOS_REQUEST = "DELETE_CASINOS_REQUEST";
export const DELETE_CASINOS_SUCCESS = "DELETE_CASINOS_SUCCESS";
export const DELETE_CASINOS_FAILURE = "DELETE_CASINOS_FAILURE";