export const FETCH_BRANCHES_REQUEST = "FETCH_BRANCHES_REQUEST";
export const FETCH_BRANCHES_SUCCESS = "FETCH_BRANCHES_SUCCESS";
export const FETCH_BRANCHES_FAILURE = "FETCH_BRANCHES_FAILURE";

export const FETCH_BRANCH_REQUEST = "FETCH_BRANCH_REQUEST";
export const FETCH_BRANCH_SUCCESS = "FETCH_BRANCH_SUCCESS";
export const FETCH_BRANCH_FAILURE = "FETCH_BRANCH_FAILURE";