export const FETCH_ESPORTSDETAILS_REQUEST = "FETCH_ESPORTSDETAILS_REQUEST";
export const FETCH_ESPORTSDETAILS_SUCCESS = "FETCH_ESPORTSDETAILS_SUCCESS";
export const FETCH_ESPORTSDETAILS_FAILURE = "FETCH_ESPORTSDETAILS_FAILURE";

export const FETCH_ESPORTSDETAILS_REQUEST = "FETCH_ESPORTSDETAILS_REQUEST";
export const FETCH_ESPORTSDETAILS_SUCCESS = "FETCH_ESPORTSDETAILS_SUCCESS";
export const FETCH_ESPORTSDETAILS_FAILURE = "FETCH_ESPORTSDETAILS_FAILURE";

export const CREATE_ESPORTSDETAILS_REQUEST = "CREATE_ESPORTSDETAILS_REQUEST";
export const CREATE_ESPORTSDETAILS_SUCCESS = "CREATE_ESPORTSDETAILS_SUCCESS";
export const CREATE_ESPORTSDETAILS_FAILURE = "CREATE_ESPORTSDETAILS_FAILURE";

export const UPDATE_ESPORTSDETAILS_REQUEST = "UPDATE_ESPORTSDETAILS_REQUEST";
export const UPDATE_ESPORTSDETAILS_SUCCESS = "UPDATE_ESPORTSDETAILS_SUCCESS";
export const UPDATE_ESPORTSDETAILS_FAILURE = "UPDATE_ESPORTSDETAILS_FAILURE";

export const DELETE_ESPORTSDETAILS_REQUEST = "DELETE_ESPORTSDETAILS_REQUEST";
export const DELETE_ESPORTSDETAILS_SUCCESS = "DELETE_ESPORTSDETAILS_SUCCESS";
export const DELETE_ESPORTSDETAILS_FAILURE = "DELETE_ESPORTSDETAILS_FAILURE";