export const FETCH_ESPORTSDETAIL_REQUEST = "FETCH_ESPORTSDETAIL_REQUEST";
export const FETCH_ESPORTSDETAIL_SUCCESS = "FETCH_ESPORTSDETAIL_SUCCESS";
export const FETCH_ESPORTSDETAIL_FAILURE = "FETCH_ESPORTSDETAIL_FAILURE";

export const FETCH_ESPORTSDETAILS_REQUEST = "FETCH_ESPORTSDETAILS_REQUEST";
export const FETCH_ESPORTSDETAILS_SUCCESS = "FETCH_ESPORTSDETAILS_SUCCESS";
export const FETCH_ESPORTSDETAILS_FAILURE = "FETCH_ESPORTSDETAILS_FAILURE";

export const CREATE_ESPORTSDETAIL_REQUEST = "CREATE_ESPORTSDETAIL_REQUEST";
export const CREATE_ESPORTSDETAIL_SUCCESS = "CREATE_ESPORTSDETAIL_SUCCESS";
export const CREATE_ESPORTSDETAIL_FAILURE = "CREATE_ESPORTSDETAIL_FAILURE";

export const UPDATE_ESPORTSDETAIL_REQUEST = "UPDATE_ESPORTSDETAIL_REQUEST";
export const UPDATE_ESPORTSDETAIL_SUCCESS = "UPDATE_ESPORTSDETAIL_SUCCESS";
export const UPDATE_ESPORTSDETAIL_FAILURE = "UPDATE_ESPORTSDETAIL_FAILURE";

export const DELETE_ESPORTSDETAILS_REQUEST = "DELETE_ESPORTSDETAILS_REQUEST";
export const DELETE_ESPORTSDETAILS_SUCCESS = "DELETE_ESPORTSDETAILS_SUCCESS";
export const DELETE_ESPORTSDETAILS_FAILURE = "DELETE_ESPORTSDETAILS_FAILURE";