export const FETCH_SALES_REQUEST = "FETCH_SALES_REQUEST";
export const FETCH_SALES_SUCCESS = "FETCH_SALES_SUCCESS";
export const FETCH_SALES_FAILURE = "FETCH_SALES_FAILURE";

export const FETCH_SALE_REQUEST = "FETCH_SALE_REQUEST";
export const FETCH_SALE_SUCCESS = "FETCH_SALE_SUCCESS";
export const FETCH_SALE_FAILURE = "FETCH_SALE_FAILURE";