export const FETCH_WITHDRAWALS_REQUEST = "FETCH_WITHDRAWALS_REQUEST";
export const FETCH_WITHDRAWALS_SUCCESS = "FETCH_WITHDRAWALS_SUCCESS";
export const FETCH_WITHDRAWALS_FAILURE = "FETCH_WITHDRAWALS_FAILURE";

export const FETCH_WITHDRAWAL_REQUEST = "FETCH_WITHDRAWAL_REQUEST";
export const FETCH_WITHDRAWAL_SUCCESS = "FETCH_WITHDRAWAL_SUCCESS";
export const FETCH_WITHDRAWAL_FAILURE = "FETCH_WITHDRAWAL_FAILURE";