export const SET_PREFERENCES = "SET_PREFERENCES";
export const SET_DARKMODE = "SET_DARKMODE";

export const FETCH_COUNTRIES_REQUEST = "FETCH_COUNTRIES_REQUEST";
export const FETCH_COUNTRIES_SUCCESS = "FETCH_COUNTRIES_SUCCESS";
export const FETCH_COUNTRIES_FAILURE = "FETCH_COUNTRIES_FAILURE";

// export const FETCH_PREFERENCE_REQUEST = "FETCH_PREFERENCE_REQUEST";
// export const FETCH_PREFERENCE_SUCCESS = "FETCH_PREFERENCE_SUCCESS";
// export const FETCH_PREFERENCE_FAILURE = "FETCH_PREFERENCE_FAILURE";

// export const CREATE_PREFERENCE_REQUEST = "CREATE_PREFERENCE_REQUEST";
// export const CREATE_PREFERENCE_SUCCESS = "CREATE_PREFERENCE_SUCCESS";
// export const CREATE_PREFERENCE_FAILURE = "CREATE_PREFERENCE_FAILURE";

// export const UPDATE_PREFERENCE_REQUEST = "UPDATE_PREFERENCE_REQUEST";
// export const UPDATE_PREFERENCE_SUCCESS = "UPDATE_PREFERENCE_SUCCESS";
// export const UPDATE_PREFERENCE_FAILURE = "UPDATE_PREFERENCE_FAILURE";

// export const DELETE_PREFERENCE_REQUEST = "DELETE_PREFERENCE_REQUEST";
// export const DELETE_PREFERENCE_SUCCESS = "DELETE_PREFERENCE_SUCCESS";
// export const DELETE_PREFERENCE_FAILURE = "DELETE_PREFERENCE_FAILURE";

export const HANDLE_USER_USERNAME = "HANDLE_USER_USERNAME";
export const HANDLE_USER_PASSWORD = "HANDLE_USER_PASSWORD";
export const HANDLE_USER_PHONENUMBER = "HANDLE_USER_PHONENUMBER";

export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAILURE = "FORGOT_PASSWORD_FAILURE";
