export const SET_PREFERENCES = "SET_PREFERENCES";
export const SET_DARKMODE = "SET_DARKMODE";

// export const FETCH_PREFERENCES_REQUEST = "FETCH_PREFERENCES_REQUEST";
// export const FETCH_PREFERENCES_SUCCESS = "FETCH_PREFERENCES_SUCCESS";
// export const FETCH_PREFERENCES_FAILURE = "FETCH_PREFERENCES_FAILURE";

// export const FETCH_PREFERENCE_REQUEST = "FETCH_PREFERENCE_REQUEST";
// export const FETCH_PREFERENCE_SUCCESS = "FETCH_PREFERENCE_SUCCESS";
// export const FETCH_PREFERENCE_FAILURE = "FETCH_PREFERENCE_FAILURE";

// export const CREATE_PREFERENCE_REQUEST = "CREATE_PREFERENCE_REQUEST";
// export const CREATE_PREFERENCE_SUCCESS = "CREATE_PREFERENCE_SUCCESS";
// export const CREATE_PREFERENCE_FAILURE = "CREATE_PREFERENCE_FAILURE";

// export const UPDATE_PREFERENCE_REQUEST = "UPDATE_PREFERENCE_REQUEST";
// export const UPDATE_PREFERENCE_SUCCESS = "UPDATE_PREFERENCE_SUCCESS";
// export const UPDATE_PREFERENCE_FAILURE = "UPDATE_PREFERENCE_FAILURE";

// export const DELETE_PREFERENCE_REQUEST = "DELETE_PREFERENCE_REQUEST";
// export const DELETE_PREFERENCE_SUCCESS = "DELETE_PREFERENCE_SUCCESS";
// export const DELETE_PREFERENCE_FAILURE = "DELETE_PREFERENCE_FAILURE";