export const SET_PREFERENCES = "SET_PREFERENCES";
export const SET_DARKMODE = "SET_DARKMODE";

export const FETCH_COUNTRIES_REQUEST = "FETCH_COUNTRIES_REQUEST";
export const FETCH_COUNTRIES_SUCCESS = "FETCH_COUNTRIES_SUCCESS";
export const FETCH_COUNTRIES_FAILURE = "FETCH_COUNTRIES_FAILURE";


export const HANDLE_USER_USERNAME = "HANDLE_USER_USERNAME";
export const HANDLE_USER_PASSWORD = "HANDLE_USER_PASSWORD";
export const HANDLE_USER_PHONENUMBER = "HANDLE_USER_PHONENUMBER";

export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAILURE = "FORGOT_PASSWORD_FAILURE";
