export const FETCH_PROMOPOSTS_REQUEST = "FETCH_PROMOPOSTS_REQUEST";
export const FETCH_PROMOPOSTS_SUCCESS = "FETCH_PROMOPOSTS_SUCCESS";
export const FETCH_PROMOPOSTS_FAILURE = "FETCH_PROMOPOSTS_FAILURE";

export const FETCH_PROMOPOST_REQUEST = "FETCH_PROMOPOST_REQUEST";
export const FETCH_PROMOPOST_SUCCESS = "FETCH_PROMOPOST_SUCCESS";
export const FETCH_PROMOPOST_FAILURE = "FETCH_PROMOPOST_FAILURE";

export const CREATE_PROMOPOST_REQUEST = "CREATE_PROMOPOST_REQUEST";
export const CREATE_PROMOPOST_SUCCESS = "CREATE_PROMOPOST_SUCCESS";
export const CREATE_PROMOPOST_FAILURE = "CREATE_PROMOPOST_FAILURE";

export const UPDATE_PROMOPOST_REQUEST = "UPDATE_PROMOPOST_REQUEST";
export const UPDATE_PROMOPOST_SUCCESS = "UPDATE_PROMOPOST_SUCCESS";
export const UPDATE_PROMOPOST_FAILURE = "UPDATE_PROMOPOST_FAILURE";

export const DELETE_PROMOPOSTS_REQUEST = "DELETE_PROMOPOSTS_REQUEST";
export const DELETE_PROMOPOSTS_SUCCESS = "DELETE_PROMOPOSTS_SUCCESS";
export const DELETE_PROMOPOSTS_FAILURE = "DELETE_PROMOPOSTS_FAILURE";