export const FETCH_GAMESVIEWS_REQUEST = "FETCH_GAMESVIEWS_REQUEST";
export const FETCH_GAMESVIEWS_SUCCESS = "FETCH_GAMESVIEWS_SUCCESS";
export const FETCH_GAMESVIEWS_FAILURE = "FETCH_GAMESVIEWS_FAILURE";

export const FETCH_GAMESVIEW_REQUEST = "FETCH_GAMESVIEW_REQUEST";
export const FETCH_GAMESVIEW_SUCCESS = "FETCH_GAMESVIEW_SUCCESS";
export const FETCH_GAMESVIEW_FAILURE = "FETCH_GAMESVIEW_FAILURE";

export const CREATE_GAMESVIEW_REQUEST = "CREATE_GAMESVIEW_REQUEST";
export const CREATE_GAMESVIEW_SUCCESS = "CREATE_GAMESVIEW_SUCCESS";
export const CREATE_GAMESVIEW_FAILURE = "CREATE_GAMESVIEW_FAILURE";

export const UPDATE_GAMESVIEW_REQUEST = "UPDATE_GAMESVIEW_REQUEST";
export const UPDATE_GAMESVIEW_SUCCESS = "UPDATE_GAMESVIEW_SUCCESS";
export const UPDATE_GAMESVIEW_FAILURE = "UPDATE_GAMESVIEW_FAILURE";

export const DELETE_GAMESVIEWS_REQUEST = "DELETE_GAMESVIEWS_REQUEST";
export const DELETE_GAMESVIEWS_SUCCESS = "DELETE_GAMESVIEWS_SUCCESS";
export const DELETE_GAMESVIEWS_FAILURE = "DELETE_GAMESVIEWS_FAILURE";