export const FETCH_INQUIRIES_REQUEST = "FETCH_INQUIRIES_REQUEST";
export const FETCH_INQUIRIES_SUCCESS = "FETCH_INQUIRIES_SUCCESS";
export const FETCH_INQUIRIES_FAILURE = "FETCH_INQUIRIES_FAILURE";

export const FETCH_INQUIRY_REQUEST = "FETCH_INQUIRY_REQUEST";
export const FETCH_INQUIRY_SUCCESS = "FETCH_INQUIRY_SUCCESS";
export const FETCH_INQUIRY_FAILURE = "FETCH_INQUIRY_FAILURE";