export const FETCH_SPORTSDETAILS_REQUEST = "FETCH_SPORTSDETAILS_REQUEST";
export const FETCH_SPORTSDETAILS_SUCCESS = "FETCH_SPORTSDETAILS_SUCCESS";
export const FETCH_SPORTSDETAILS_FAILURE = "FETCH_SPORTSDETAILS_FAILURE";

export const FETCH_SPORTSDETAIL_REQUEST = "FETCH_SPORTSDETAIL_REQUEST";
export const FETCH_SPORTSDETAIL_SUCCESS = "FETCH_SPORTSDETAIL_SUCCESS";
export const FETCH_SPORTSDETAIL_FAILURE = "FETCH_SPORTSDETAIL_FAILURE";
export const SPORTSDETAIL_RESET = "SPORTSDETAIL_RESET";
export const GET_SPORTSDETAILS = "GET_SPORTSDETAILS";


export const CREATE_SPORTSDETAIL_REQUEST = "CREATE_SPORTSDETAIL_REQUEST";
export const CREATE_SPORTSDETAIL_SUCCESS = "CREATE_SPORTSDETAIL_SUCCESS";
export const CREATE_SPORTSDETAIL_FAILURE = "CREATE_SPORTSDETAIL_FAILURE";

export const UPDATE_SPORTSDETAIL_REQUEST = "UPDATE_SPORTSDETAIL_REQUEST";
export const UPDATE_SPORTSDETAIL_SUCCESS = "UPDATE_SPORTSDETAIL_SUCCESS";
export const UPDATE_SPORTSDETAIL_FAILURE = "UPDATE_SPORTSDETAIL_FAILURE";

export const DELETE_SPORTSDETAILS_REQUEST = "DELETE_SPORTSDETAILS_REQUEST";
export const DELETE_SPORTSDETAILS_SUCCESS = "DELETE_SPORTSDETAILS_SUCCESS";
export const DELETE_SPORTSDETAILS_FAILURE = "DELETE_SPORTSDETAILS_FAILURE";